theme:
    name: 'material'
    palette:
        primary: 'indigo'
        accent: 'indigo'
    feature:
        tabs: true
markdown_extensions:
  - meta

site_name: Levridge Documentation
repo_name: 'levridge-tory.github.io/LevridgeIntegrationDocs'
repo_url: 'https://github.com/Levridge-Tory/LevridgeIntegrationDocs'
nav:
    - Home: index.md
    - Products:
        - Levridge Core:
            - Integration Framework:
                - Overview : 'Integration-Overview.md'
                - Integrations:
                    - 'D365 CRM to D365 F&O' : 'D365-CRM-to-D365-F&O.md'
                    - 'D365 F&O to D365 CRM' : 'D365-F&O-to-D365-CRM.md'
                    - 'Levridge Scale House' : 'scale-integration.md'
                    - 'Agsync' : 'Agsync.md'
                    - 'Kahler' : 'Kahler.md'
                    - 'Surety' : 'Surety.md'
                    - 'oneWeigh' : 'oneWeigh.md'
                    - 'Field Reveal' : 'Field-Reveal.md'
                    - 'Integrating Custom Fields':'IntegratingCustomFields.md'
                - Deployment: 
                    - 'Deploying the Integration Framework' : 'Deploying-Integration-Framework.md'
                    - 'Application Settings Configuration' : 'ApplicationConfiguration.md'
                    - 'Deploying Custom Field Mapping Assemblies': 'DeployingCustomFieldMappingAssemblies.md'
                    - 'Deploying CDS' : 'DeployingCDS.md'
            - Print Service: 'print-service.md'
            - CRM Platform:
                - CRM Platform Configuration : 'CRM-configuration.md'
        - Levridge Agronomy: 'Agronomy.md'
        - Levridge Commodities: 'Commodities.md'
        - Levridge Feed: 'Feed.md'
        - Levridge Equity Accounting: 'Equity.md'
        - Levridge Scale : 
            - Scale Overview : 'Scale-Overview.md'
            - Scale Installation : 'scale-install-settings-instructions.md'
    - User Documentation:
        - 'Finance & Operations' :
            - Accounts Receivable Setup :
                - 'Create a New Split Group': 'Create-Split-Group-in-F&O.md'
        - Inventory Value and Costing :
            - Upload Standard Cost Pricing: 'UploadStandardCostPricing.md'
            - Adjust FIFO Inventory Value: 'AdjustFIFOInventoryValue.md'
            - Setup Cost Variances: 'SetupCostVariances.md'
            - Close Inventory: 'CloseInventory.md'
            - Setup a Standard Cost: 'SetupStandardCost.md'
        - Procurement Hierarchy :
            - Create a Purchase Requisition and Consolidation: 'CreatePurchaseRequistionAndConsolidation.md'
            - Purchasing Policy Assignment: 'PurchasingPolicyAssignment.md'
            - Publish Catalog: 'PublishCatalog.md'
            - Create a Procurement Category: 'CreateProcurementCategory.md'
            - Create a Procurement Hierarchy: 'CreateProcurementHierarchy.md'
            - Assign Item to a Procurement Category: 'AssignItemToProcurementCategory.md'
            - Assign Posting Profile to Procuremnet Category: 'AssignPostingProfiletoProcurementCategory.md'
        - Vendor Customer Pricing :
            - Trade Agreements Price Group : 'TradeAgreementsPriceGroup.md'
            - Basic Vendor Price with Price Update : 'BasicVendorPriceWithPriceUpdate.md'
            - Basic Vendor Purchase Price : 'BasicVendorPurchasePrice.md'
            - Basic Customer Price Setup : 'BasicCustomerPriceSetup.md'
        - RFQ : 'RFQ.md'
        - Commissions : 'Commissions.md'
        - Customer:
            - Add Address for Delivery and Invoice : 'AddAddressForDeliveryAndInvoice.md'
            - Customer Template : 'CustomerTemplate.md'
            - Customer Creation Organization : 'CustomerCreationOrganization.md'
    - About: about.md
