site_name: Levridge Documentation
nav:
    - Home: index.md
    - Products:
        - Levridge Core:
            - Integration Framework:
                - Overview : 'Integration-Overview.md'
                - Integrations:
                    - 'D365 CRM to D365 F&O' : 'D365-CRM-to-D365-F&O.md'
                    - 'D365 F&O to D365 CRM' : 'D365-F&O-to-D365-CRM.md'
                    - 'Levridge Scale House' : 'scale-integration.md'
                    - 'Agsync' : 'Agsync.md'
                    - 'Kahler' : 'Kahler.md'
                    - 'Surety' : 'Surety.md'
                    - 'oneWeigh' : 'oneWeigh.md'
                    - 'Field Reveal' : 'Field-Reveal.md'
                - Deployment: 
                    - 'Deploying the Integration Framework' : 'Deploying-Integration-Framework.md'
                    - 'Deploying CDS' : 'DeployingCDS.md'
            - Print Service: 'print-service.md'
            - CRM Platform:
                - CRM Platform Configuration : 'CRM-configuration.md'
        - Levridge Agronomy: 'Agronomy.md'
        - Levridge Commodities: 'Commodities.md'
        - Levridge Feed: 'Feed.md'
        - Levridge Equity Accounting: 'Equity.md'
        - Levridge Scale : 
            - Scale Overview : 'Scale-Overview.md'
            - Scale Installation : 'scale.md'
    - About: about.md
    - User Documentation:
        - Inventory Value and Costing :
            - Upload Standard Cost Pricing: 'UploadStandardCostPricing.md'
            - Adjust FIFO Inventory Value: 'AdjustFIFOInventoryValue.md'
            - Setup Cost Variances: 'SetupCostVariances.md'
            - Close Inventory: 'CloseInventory.md'
            - Setup a Standard Cost: 'SetupStandardCost.md'
        - Procurement Hierarchy :
            - Create a Purchase Requisition and Consolidation: 'CreatePurchaseRequistionAndConsolidation.md'
            - Purchasing Policy Assignment: 'PurchasingPolicyAssignment.md'
            - Publish Catalog: 'PublishCatalog.md'
            - Create a Procurement Category: 'CreateProcurementCategory.md'
            - Create a Procurement Hierarchy: 'CreateProcurementHierarchy.md'
            - Assign Item to a Procurement Category: 'AssignItemToProcumentCategory.md'
            - Assign Posting Profile to Procuremnet Category: 'AssignPostpingProfiletoProcuremnetCategory.md'