theme:
    name: 'material'
    palette:
        primary: 'indigo'
        accent: 'indigo'
    feature:
        tabs: true
markdown_extensions:
  - meta
  - toc:
        anchorlink: True

site_name: Levridge Documentation
repo_name: 'levridge-tory.github.io/LevridgeIntegrationDocs'
repo_url: 'https://github.com/Levridge-Tory/LevridgeIntegrationDocs'
nav:
    - Home: index.md
    - Products:
        - Agronomy: 'Agronomy.md'
        - Agronomy Retail: 'AgronomyRetail.md'
        - Commodity Accounting: 'Commodities.md'
        - Feed: 'Feed.md'
        - Equity Management: 'Patronage.md'
        - Scale: 
            - Scale Overview : 'Scale-Overview.md'
            - Scale Settings Configuration : 'scale-settings-configuration.md' 
        - System Information:
            - Integration Framework:
                - Overview : 'Integration-Overview.md'
                - Integrations :
                    - 'D365 CE to D365 F&O' : 'D365-CE-to-D365-F&O.md'
                    - 'D365 F&O to D365 CE' : 'D365-F&O-to-D365-CE.md'
                    - 'Scale' : 'scale-integration.md'
                    - 'Agsync' : 'Agsync.md'
                    - 'Kahler' : 'Kahler.md'
                    - 'Surety' : 'Surety.md'
                    - 'oneWeigh' : 'oneWeigh.md'
                    - 'Field Reveal' : 'Field-Reveal.md'
                    - 'Integrating Custom Fields' : 'IntegratingCustomFields.md'
                - Deployment: 
                    - 'Deploying the Integration Framework' : 'Deploying-Integration-Framework.md'
                    - 'Application Settings Configuration' : 'ApplicationConfiguration.md'
                    - 'Deploying Custom Field Mapping Assemblies': 'DeployingCustomFieldMappingAssemblies.md'
                    - 'Deploying CDS' : 'DeployingCDS.md'
            - Print Service: 'print-service.md'
            - CE Platform:
                - CE Platform Configuration : 'CE-configuration.md'
            - Environment Planning : 'EnvironmentPlanning.md'
